### ISSUE TITLE
Rule no-dob crash on forin and forof loops 

### ISSUE THREAD

**Issue by MrZyr0** [shiva-hack/eslint-plugin-pii#1]
Hi :wave:

Thank you so much for your awesome work !

I use it in my new project and I've notice an issue with the rule `pii/no-dob`.

It seems that this one does not support check on for loops like `forin` and `forof`.

**How to reproduce**:

```javascript
const myArray = [];
for (const iterator of myArray) {
    console.log(interator);
}
```

Output:
```
[Error - 10:26:22 PM] ESLint stack trace:
[Error - 10:26:22 PM] TypeError: Cannot read property 'type' of null
Occurred while linting /Users/Zyr0/Project/test.mjs:27
Rule: "pii/no-dob"
    at VariableDeclarator (/Users/Zyr0/Project/node_modules/eslint-plugin-pii/lib/rules/no-dob.js:71:45)
    at ruleErrorHandler (/Users/Zyr0/Project/node_modules/eslint/lib/linter/linter.js:966:28)
    at /Users/Zyr0/Project/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/Zyr0/Project/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/Zyr0/Project/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/Users/Zyr0/Project/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/Users/Zyr0/Project/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/Users/Zyr0/Project/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:790:23)
    at /Users/Zyr0/Project/node_modules/eslint/lib/linter/linter.js:997:32
```

**Comment by MrZyr0** [comment]
Any news ?

**Comment by shiva-hack** [comment]
@MrZyr0 , going to merge this later today

**Comment by jz222** [comment]
Hi @shiva-hack any updates? Thank you
